//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.269
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flexible_computing.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flexible_computing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arithmetic_exception {
            get {
                object obj = ResourceManager.GetObject("arithmetic_exception", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_in {
            get {
                object obj = ResourceManager.GetObject("arrow_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_out {
            get {
                object obj = ResourceManager.GetObject("arrow_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.6810515715560467531e-4932.
        /// </summary>
        internal static string d_128_0 {
            get {
                return ResourceManager.GetString("d_128_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.4052578577802337657e-4933.
        /// </summary>
        internal static string d_128_1 {
            get {
                return ResourceManager.GetString("d_128_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.6416519253477019074e-4935.
        /// </summary>
        internal static string d_128_10 {
            get {
                return ResourceManager.GetString("d_128_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.3261158644609075427e-4962.
        /// </summary>
        internal static string d_128_100 {
            get {
                return ResourceManager.GetString("d_128_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.6305793223045377136e-4963.
        /// </summary>
        internal static string d_128_101 {
            get {
                return ResourceManager.GetString("d_128_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.3152896611522688568e-4963.
        /// </summary>
        internal static string d_128_102 {
            get {
                return ResourceManager.GetString("d_128_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.6576448305761344284e-4963.
        /// </summary>
        internal static string d_128_103 {
            get {
                return ResourceManager.GetString("d_128_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.2082596267385095368e-4936.
        /// </summary>
        internal static string d_128_11 {
            get {
                return ResourceManager.GetString("d_128_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.1041298133692547684e-4936.
        /// </summary>
        internal static string d_128_12 {
            get {
                return ResourceManager.GetString("d_128_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.0520649066846273842e-4936.
        /// </summary>
        internal static string d_128_13 {
            get {
                return ResourceManager.GetString("d_128_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.0260324533423136921e-4936.
        /// </summary>
        internal static string d_128_14 {
            get {
                return ResourceManager.GetString("d_128_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.1301622667115684605e-4937.
        /// </summary>
        internal static string d_128_15 {
            get {
                return ResourceManager.GetString("d_128_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.5650811333557842302e-4937.
        /// </summary>
        internal static string d_128_16 {
            get {
                return ResourceManager.GetString("d_128_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.2825405666778921151e-4937.
        /// </summary>
        internal static string d_128_17 {
            get {
                return ResourceManager.GetString("d_128_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.4127028333894605756e-4938.
        /// </summary>
        internal static string d_128_18 {
            get {
                return ResourceManager.GetString("d_128_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.2063514166947302878e-4938.
        /// </summary>
        internal static string d_128_19 {
            get {
                return ResourceManager.GetString("d_128_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.2026289288901168828e-4933.
        /// </summary>
        internal static string d_128_2 {
            get {
                return ResourceManager.GetString("d_128_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.6031757083473651439e-4938.
        /// </summary>
        internal static string d_128_20 {
            get {
                return ResourceManager.GetString("d_128_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.0158785417368257195e-4939.
        /// </summary>
        internal static string d_128_21 {
            get {
                return ResourceManager.GetString("d_128_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.0079392708684128598e-4939.
        /// </summary>
        internal static string d_128_22 {
            get {
                return ResourceManager.GetString("d_128_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.0039696354342064299e-4939.
        /// </summary>
        internal static string d_128_23 {
            get {
                return ResourceManager.GetString("d_128_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.0019848177171032149e-4939.
        /// </summary>
        internal static string d_128_24 {
            get {
                return ResourceManager.GetString("d_128_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.0099240885855160747e-4940.
        /// </summary>
        internal static string d_128_25 {
            get {
                return ResourceManager.GetString("d_128_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.5049620442927580373e-4940.
        /// </summary>
        internal static string d_128_26 {
            get {
                return ResourceManager.GetString("d_128_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.2524810221463790187e-4940.
        /// </summary>
        internal static string d_128_27 {
            get {
                return ResourceManager.GetString("d_128_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.2624051107318950934e-4941.
        /// </summary>
        internal static string d_128_28 {
            get {
                return ResourceManager.GetString("d_128_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.1312025553659475467e-4941.
        /// </summary>
        internal static string d_128_29 {
            get {
                return ResourceManager.GetString("d_128_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.1013144644450584414e-4933.
        /// </summary>
        internal static string d_128_3 {
            get {
                return ResourceManager.GetString("d_128_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.5656012776829737733e-4941.
        /// </summary>
        internal static string d_128_30 {
            get {
                return ResourceManager.GetString("d_128_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.8280063884148688667e-4942.
        /// </summary>
        internal static string d_128_31 {
            get {
                return ResourceManager.GetString("d_128_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.9140031942074344334e-4942.
        /// </summary>
        internal static string d_128_32 {
            get {
                return ResourceManager.GetString("d_128_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.9570015971037172167e-4942.
        /// </summary>
        internal static string d_128_33 {
            get {
                return ResourceManager.GetString("d_128_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9.7850079855185860834e-4943.
        /// </summary>
        internal static string d_128_34 {
            get {
                return ResourceManager.GetString("d_128_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.8925039927592930417e-4943.
        /// </summary>
        internal static string d_128_35 {
            get {
                return ResourceManager.GetString("d_128_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.4462519963796465208e-4943.
        /// </summary>
        internal static string d_128_36 {
            get {
                return ResourceManager.GetString("d_128_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.2231259981898232604e-4943.
        /// </summary>
        internal static string d_128_37 {
            get {
                return ResourceManager.GetString("d_128_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.1156299909491163021e-4944.
        /// </summary>
        internal static string d_128_38 {
            get {
                return ResourceManager.GetString("d_128_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.0578149954745581511e-4944.
        /// </summary>
        internal static string d_128_39 {
            get {
                return ResourceManager.GetString("d_128_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.0506572322225292207e-4933.
        /// </summary>
        internal static string d_128_4 {
            get {
                return ResourceManager.GetString("d_128_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.5289074977372790755e-4944.
        /// </summary>
        internal static string d_128_40 {
            get {
                return ResourceManager.GetString("d_128_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.6445374886863953776e-4945.
        /// </summary>
        internal static string d_128_41 {
            get {
                return ResourceManager.GetString("d_128_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.8222687443431976888e-4945.
        /// </summary>
        internal static string d_128_42 {
            get {
                return ResourceManager.GetString("d_128_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.9111343721715988444e-4945.
        /// </summary>
        internal static string d_128_43 {
            get {
                return ResourceManager.GetString("d_128_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9.5556718608579942221e-4946.
        /// </summary>
        internal static string d_128_44 {
            get {
                return ResourceManager.GetString("d_128_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.7778359304289971110e-4946.
        /// </summary>
        internal static string d_128_45 {
            get {
                return ResourceManager.GetString("d_128_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.3889179652144985555e-4946.
        /// </summary>
        internal static string d_128_46 {
            get {
                return ResourceManager.GetString("d_128_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.1944589826072492778e-4946.
        /// </summary>
        internal static string d_128_47 {
            get {
                return ResourceManager.GetString("d_128_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.9722949130362463888e-4947.
        /// </summary>
        internal static string d_128_48 {
            get {
                return ResourceManager.GetString("d_128_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.9861474565181231944e-4947.
        /// </summary>
        internal static string d_128_49 {
            get {
                return ResourceManager.GetString("d_128_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.2532861611126461035e-4934.
        /// </summary>
        internal static string d_128_5 {
            get {
                return ResourceManager.GetString("d_128_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.4930737282590615972e-4947.
        /// </summary>
        internal static string d_128_50 {
            get {
                return ResourceManager.GetString("d_128_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.4653686412953079860e-4948.
        /// </summary>
        internal static string d_128_51 {
            get {
                return ResourceManager.GetString("d_128_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.7326843206476539930e-4948.
        /// </summary>
        internal static string d_128_52 {
            get {
                return ResourceManager.GetString("d_128_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.8663421603238269965e-4948.
        /// </summary>
        internal static string d_128_53 {
            get {
                return ResourceManager.GetString("d_128_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9.3317108016191349825e-4949.
        /// </summary>
        internal static string d_128_54 {
            get {
                return ResourceManager.GetString("d_128_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.6658554008095674912e-4949.
        /// </summary>
        internal static string d_128_55 {
            get {
                return ResourceManager.GetString("d_128_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.3329277004047837456e-4949.
        /// </summary>
        internal static string d_128_56 {
            get {
                return ResourceManager.GetString("d_128_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.1664638502023918728e-4949.
        /// </summary>
        internal static string d_128_57 {
            get {
                return ResourceManager.GetString("d_128_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.8323192510119593640e-4950.
        /// </summary>
        internal static string d_128_58 {
            get {
                return ResourceManager.GetString("d_128_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.9161596255059796820e-4950.
        /// </summary>
        internal static string d_128_59 {
            get {
                return ResourceManager.GetString("d_128_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.6266430805563230518e-4934.
        /// </summary>
        internal static string d_128_6 {
            get {
                return ResourceManager.GetString("d_128_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.4580798127529898410e-4950.
        /// </summary>
        internal static string d_128_60 {
            get {
                return ResourceManager.GetString("d_128_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.2903990637649492051e-4951.
        /// </summary>
        internal static string d_128_61 {
            get {
                return ResourceManager.GetString("d_128_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.6451995318824746025e-4951.
        /// </summary>
        internal static string d_128_62 {
            get {
                return ResourceManager.GetString("d_128_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.8225997659412373013e-4951.
        /// </summary>
        internal static string d_128_63 {
            get {
                return ResourceManager.GetString("d_128_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9.1129988297061865063e-4952.
        /// </summary>
        internal static string d_128_64 {
            get {
                return ResourceManager.GetString("d_128_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.5564994148530932532e-4952.
        /// </summary>
        internal static string d_128_65 {
            get {
                return ResourceManager.GetString("d_128_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.2782497074265466266e-4952.
        /// </summary>
        internal static string d_128_66 {
            get {
                return ResourceManager.GetString("d_128_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.1391248537132733133e-4952.
        /// </summary>
        internal static string d_128_67 {
            get {
                return ResourceManager.GetString("d_128_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.6956242685663665665e-4953.
        /// </summary>
        internal static string d_128_68 {
            get {
                return ResourceManager.GetString("d_128_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.8478121342831832832e-4953.
        /// </summary>
        internal static string d_128_69 {
            get {
                return ResourceManager.GetString("d_128_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.3133215402781615259e-4934.
        /// </summary>
        internal static string d_128_7 {
            get {
                return ResourceManager.GetString("d_128_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.4239060671415916416e-4953.
        /// </summary>
        internal static string d_128_70 {
            get {
                return ResourceManager.GetString("d_128_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.1195303357079582081e-4954.
        /// </summary>
        internal static string d_128_71 {
            get {
                return ResourceManager.GetString("d_128_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.5597651678539791040e-4954.
        /// </summary>
        internal static string d_128_72 {
            get {
                return ResourceManager.GetString("d_128_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.7798825839269895520e-4954.
        /// </summary>
        internal static string d_128_73 {
            get {
                return ResourceManager.GetString("d_128_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.8994129196349477601e-4955.
        /// </summary>
        internal static string d_128_74 {
            get {
                return ResourceManager.GetString("d_128_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.4497064598174738800e-4955.
        /// </summary>
        internal static string d_128_75 {
            get {
                return ResourceManager.GetString("d_128_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.2248532299087369400e-4955.
        /// </summary>
        internal static string d_128_76 {
            get {
                return ResourceManager.GetString("d_128_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.1124266149543684700e-4955.
        /// </summary>
        internal static string d_128_77 {
            get {
                return ResourceManager.GetString("d_128_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.5621330747718423500e-4956.
        /// </summary>
        internal static string d_128_78 {
            get {
                return ResourceManager.GetString("d_128_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.7810665373859211750e-4956.
        /// </summary>
        internal static string d_128_79 {
            get {
                return ResourceManager.GetString("d_128_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.5666077013908076294e-4935.
        /// </summary>
        internal static string d_128_8 {
            get {
                return ResourceManager.GetString("d_128_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.3905332686929605875e-4956.
        /// </summary>
        internal static string d_128_80 {
            get {
                return ResourceManager.GetString("d_128_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.9526663434648029376e-4957.
        /// </summary>
        internal static string d_128_81 {
            get {
                return ResourceManager.GetString("d_128_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.4763331717324014688e-4957.
        /// </summary>
        internal static string d_128_82 {
            get {
                return ResourceManager.GetString("d_128_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.7381665858662007344e-4957.
        /// </summary>
        internal static string d_128_83 {
            get {
                return ResourceManager.GetString("d_128_83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.6908329293310036720e-4958.
        /// </summary>
        internal static string d_128_84 {
            get {
                return ResourceManager.GetString("d_128_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.3454164646655018360e-4958.
        /// </summary>
        internal static string d_128_85 {
            get {
                return ResourceManager.GetString("d_128_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.1727082323327509180e-4958.
        /// </summary>
        internal static string d_128_86 {
            get {
                return ResourceManager.GetString("d_128_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.0863541161663754590e-4958.
        /// </summary>
        internal static string d_128_87 {
            get {
                return ResourceManager.GetString("d_128_87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.4317705808318772950e-4959.
        /// </summary>
        internal static string d_128_88 {
            get {
                return ResourceManager.GetString("d_128_88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.7158852904159386475e-4959.
        /// </summary>
        internal static string d_128_89 {
            get {
                return ResourceManager.GetString("d_128_89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.2833038506954038147e-4935.
        /// </summary>
        internal static string d_128_9 {
            get {
                return ResourceManager.GetString("d_128_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.3579426452079693237e-4959.
        /// </summary>
        internal static string d_128_90 {
            get {
                return ResourceManager.GetString("d_128_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.7897132260398466187e-4960.
        /// </summary>
        internal static string d_128_91 {
            get {
                return ResourceManager.GetString("d_128_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.3948566130199233094e-4960.
        /// </summary>
        internal static string d_128_92 {
            get {
                return ResourceManager.GetString("d_128_92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.6974283065099616547e-4960.
        /// </summary>
        internal static string d_128_93 {
            get {
                return ResourceManager.GetString("d_128_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.4871415325498082734e-4961.
        /// </summary>
        internal static string d_128_94 {
            get {
                return ResourceManager.GetString("d_128_94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.2435707662749041367e-4961.
        /// </summary>
        internal static string d_128_95 {
            get {
                return ResourceManager.GetString("d_128_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.1217853831374520683e-4961.
        /// </summary>
        internal static string d_128_96 {
            get {
                return ResourceManager.GetString("d_128_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.0608926915687260342e-4961.
        /// </summary>
        internal static string d_128_97 {
            get {
                return ResourceManager.GetString("d_128_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.3044634578436301709e-4962.
        /// </summary>
        internal static string d_128_98 {
            get {
                return ResourceManager.GetString("d_128_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.6522317289218150854e-4962.
        /// </summary>
        internal static string d_128_99 {
            get {
                return ResourceManager.GetString("d_128_99", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap demon_blood {
            get {
                object obj = ResourceManager.GetObject("demon_blood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap double_lined {
            get {
                object obj = ResourceManager.GetObject("double_lined", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pbinary32.
        /// </summary>
        internal static string Format32_TypeInt {
            get {
                return ResourceManager.GetString("Format32_TypeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pbinary64f.
        /// </summary>
        internal static string Format64_TypeF {
            get {
                return ResourceManager.GetString("Format64_TypeF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pbinary64i.
        /// </summary>
        internal static string Format64_TypeI {
            get {
                return ResourceManager.GetString("Format64_TypeI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pbinary64.
        /// </summary>
        internal static string Format64_TypeInt {
            get {
                return ResourceManager.GetString("Format64_TypeInt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap function_exception {
            get {
                object obj = ResourceManager.GetObject("function_exception", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap general_exception {
            get {
                object obj = ResourceManager.GetObject("general_exception", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap light_honeycomb {
            get {
                object obj = ResourceManager.GetObject("light_honeycomb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mesbox_info16 {
            get {
                object obj = ResourceManager.GetObject("mesbox_info16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop_thread {
            get {
                object obj = ResourceManager.GetObject("stop_thread", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop_thread2 {
            get {
                object obj = ResourceManager.GetObject("stop_thread2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap success {
            get {
                object obj = ResourceManager.GetObject("success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
